### PR TITLE
Corrected the Header for Homegrown Software

### PR DESCRIPTION
**Pull request by hamidshojaee**

### CODE REVIEW

**Comment by hamidshojaee** [comment]
By the way, I don't think all of the software listed in the Homegrown Software section is open-source, but since you removed my products (GitKraken, Glo and Pure Chat) due to not being open source, it makes sense for the header of the section to indicate it's just a list of open source projects from Phoenix.

**Comment by monteslu** [comment]
Maybe we make two sections so we can feature open source and other projects?

**Comment by monteslu** [comment]
The stuff coming from Hamid's team definitely should be featured on awesome-phx

**Comment by samrocksc** [comment]
I actually totally agree with this.  Knowing how much work has been put into Glo/GitKraken, I also think they are both awesome.  I had some feedback though on keeping the Homegrown section emphasized on open source software.  I actually agree that Open Source should take precedence over for-profit product.

One reason I don't want to get into the for-profit listings is because there is a lot of grey area on what a "product" is...there's also marketing software, which is in nature "tech"; however, it's something we have to watch and monitor.  This increases the actual responsibility of the list to vet the products we allow to be added to it.

I feel like it's a disservice to list an unmaintained or unfinished product next to something that is a finished and functional product actually...

I think listing a company's website that has products for-profit is sufficient, and also a good filter for professionalism.

I'm all for opening and branching to like a second page where for-profit software is included in a secondary page; however, I'd like to see open-source software emphasized.  I think we can work with this and further this really well.

**Comment by samrocksc** [comment]
Also, caveat, we should probably vet the list as is currently and check it out.  I'll do that this evening.

**Comment by hamidshojaee** [comment]
I don't have a problem with listing only "Homegrown Open-Source Software" but at least the header should be clear. 

Separately, you might have an issue with open-source projects, because does "homegrown" mean the project was started by a person in Arizona (even if most contributors are elsewhere) or does it include projects where a bunch/most of contributors are from Arizona?

**Comment by w33ble** [comment]
Another option, we *could* just remove the software section entirely. It seems to have started out as [kind of a joke anyway](https://github.com/samrocksc/awesome-phoenix/commit/70923609d98e737b954b49bb26a982a450d4e8c0).

**Pull request merged**
