### PR TITLE
updates

### PR DESCRIPTION
**Pull request by monteslu**

### CODE REVIEW

**Review by w33ble — CHANGES_REQUESTED** [review]
This doesn't look like an open source project, I think it should be under the Companies section instead.

**Comment by monteslu** [comment]
@w33ble you're right. I didnt fully read that section header.  Will fix.

**Comment by samrocksc** [comment]
@monteslu did you still want to update this?

**Comment by monteslu** [comment]
@w33ble @samrocksc 

fixed and added a bunch more stuff

**Review by w33ble — APPROVED** [review]

**Pull request merged**
